name: ${project.artifactId}
version: ${project.version}
description: Plugin that changes Players name color on their command.
author: [ Nate Legault, blockparole ]
main: leee.nc.LeeesNC

commands:
  nc:
    description: Change your name color.
    aliases: [ namecolor, namecolour ]
